// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company.sql

package sqlcgen

import (
	"context"
)

const companyExists = `-- name: CompanyExists :one
SELECT EXISTS (SELECT 1 FROM company WHERE symbol = $1)
`

func (q *Queries) CompanyExists(ctx context.Context, symbol string) (bool, error) {
	row := q.db.QueryRow(ctx, companyExists, symbol)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCompanies = `-- name: CountCompanies :one
SELECT count(*) FROM company
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompany = `-- name: GetCompany :one
SELECT symbol, name, created_at, updated_at
FROM company
WHERE symbol = $1
`

func (q *Queries) GetCompany(ctx context.Context, symbol string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, symbol)
	var i Company
	err := row.Scan(
		&i.Symbol,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompany = `-- name: UpsertCompany :exec
INSERT INTO company (symbol, name)
VALUES ($1, $2)
ON CONFLICT (symbol) DO UPDATE
    SET name       = EXCLUDED.name,
        updated_at = now()
WHERE company.name IS DISTINCT FROM EXCLUDED.name
`

type UpsertCompanyParams struct {
	Symbol string
	Name   string
}

// The update time only moves when something actually changed, so it means
// "last changed" rather than "last seen by the importer", which is what
// AIP-142's update_time is defined to mean.
func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.Exec(ctx, upsertCompany, arg.Symbol, arg.Name)
	return err
}
