// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dividend.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDividend = `-- name: GetDividend :one
SELECT id, company_symbol, year, dividend_type,
       gross_per_share_natural_person, gross_per_share_legal_person, total_amount,
       announcement_date, gms_reference_date, gms_date, record_date,
       ex_dividend_date, payment_start_date, payment_end_date,
       distribution_method, created_at, updated_at
FROM dividend
WHERE id = $1
`

func (q *Queries) GetDividend(ctx context.Context, id uuid.UUID) (Dividend, error) {
	row := q.db.QueryRow(ctx, getDividend, id)
	var i Dividend
	err := row.Scan(
		&i.ID,
		&i.CompanySymbol,
		&i.Year,
		&i.DividendType,
		&i.GrossPerShareNaturalPerson,
		&i.GrossPerShareLegalPerson,
		&i.TotalAmount,
		&i.AnnouncementDate,
		&i.GmsReferenceDate,
		&i.GmsDate,
		&i.RecordDate,
		&i.ExDividendDate,
		&i.PaymentStartDate,
		&i.PaymentEndDate,
		&i.DistributionMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDividend = `-- name: UpsertDividend :execrows
INSERT INTO dividend (id, company_symbol, year, dividend_type,
                      gross_per_share_natural_person, gross_per_share_legal_person, total_amount,
                      announcement_date, gms_reference_date, gms_date, record_date,
                      ex_dividend_date, payment_start_date, payment_end_date,
                      distribution_method)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE
    SET company_symbol                 = EXCLUDED.company_symbol,
        year                           = EXCLUDED.year,
        dividend_type                  = EXCLUDED.dividend_type,
        gross_per_share_natural_person = EXCLUDED.gross_per_share_natural_person,
        gross_per_share_legal_person   = EXCLUDED.gross_per_share_legal_person,
        total_amount                   = EXCLUDED.total_amount,
        announcement_date              = EXCLUDED.announcement_date,
        gms_reference_date             = EXCLUDED.gms_reference_date,
        gms_date                       = EXCLUDED.gms_date,
        record_date                    = EXCLUDED.record_date,
        ex_dividend_date               = EXCLUDED.ex_dividend_date,
        payment_start_date             = EXCLUDED.payment_start_date,
        payment_end_date               = EXCLUDED.payment_end_date,
        distribution_method            = EXCLUDED.distribution_method,
        updated_at                     = now()
WHERE (dividend.gross_per_share_natural_person, dividend.gross_per_share_legal_person,
       dividend.total_amount, dividend.announcement_date, dividend.gms_reference_date,
       dividend.gms_date, dividend.record_date, dividend.payment_start_date,
       dividend.payment_end_date, dividend.distribution_method)
      IS DISTINCT FROM
      (EXCLUDED.gross_per_share_natural_person, EXCLUDED.gross_per_share_legal_person,
       EXCLUDED.total_amount, EXCLUDED.announcement_date, EXCLUDED.gms_reference_date,
       EXCLUDED.gms_date, EXCLUDED.record_date, EXCLUDED.payment_start_date,
       EXCLUDED.payment_end_date, EXCLUDED.distribution_method)
`

type UpsertDividendParams struct {
	ID                         uuid.UUID
	CompanySymbol              string
	Year                       int32
	DividendType               string
	GrossPerShareNaturalPerson pgtype.Numeric
	GrossPerShareLegalPerson   pgtype.Numeric
	TotalAmount                pgtype.Numeric
	AnnouncementDate           pgtype.Date
	GmsReferenceDate           pgtype.Date
	GmsDate                    pgtype.Date
	RecordDate                 pgtype.Date
	ExDividendDate             pgtype.Date
	PaymentStartDate           pgtype.Date
	PaymentEndDate             pgtype.Date
	DistributionMethod         string
}

// Conflicts resolve on the identifier, which is derived from the dividend's
// natural key, so a re-import updates the row it created the first time rather
// than inserting a second copy. The creation time and the resource name
// therefore survive for as long as BVB keeps reporting the dividend.
func (q *Queries) UpsertDividend(ctx context.Context, arg UpsertDividendParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDividend,
		arg.ID,
		arg.CompanySymbol,
		arg.Year,
		arg.DividendType,
		arg.GrossPerShareNaturalPerson,
		arg.GrossPerShareLegalPerson,
		arg.TotalAmount,
		arg.AnnouncementDate,
		arg.GmsReferenceDate,
		arg.GmsDate,
		arg.RecordDate,
		arg.ExDividendDate,
		arg.PaymentStartDate,
		arg.PaymentEndDate,
		arg.DistributionMethod,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
