// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	Symbol    string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Dividend struct {
	ID                         uuid.UUID
	CompanySymbol              string
	Year                       int32
	DividendType               string
	GrossPerShareNaturalPerson pgtype.Numeric
	GrossPerShareLegalPerson   pgtype.Numeric
	TotalAmount                pgtype.Numeric
	AnnouncementDate           pgtype.Date
	GmsReferenceDate           pgtype.Date
	GmsDate                    pgtype.Date
	RecordDate                 pgtype.Date
	ExDividendDate             pgtype.Date
	PaymentStartDate           pgtype.Date
	PaymentEndDate             pgtype.Date
	DistributionMethod         string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}
