// Copyright 2026 The BVB Dividends Authors.
//
// Resource definitions for companies listed on the Bucharest Stock Exchange.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: bvb/dividends/v1/company.proto

package dividendsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A company listed on the Bucharest Stock Exchange (Bursa de Valori Bucuresti).
//
// Companies are discovered from the BVB financials web service; they are never
// created directly through this API.
type Company struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The resource name of the company.
	//
	// Format: `companies/{company}`, where `{company}` is the BVB ticker symbol,
	// for example `companies/SNP`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output only. The BVB ticker symbol, for example `SNP`.
	//
	// This is the same value as the `{company}` segment of `name`, exposed as a
	// field for convenience and filtering.
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Output only. The full legal name of the company, for example
	// `OMV PETROM S.A.`, as reported by BVB.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Output only. The time this company was first imported from BVB.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. The time this company was last refreshed from BVB.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_bvb_dividends_v1_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_company_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Company) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Company) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Company) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_bvb_dividends_v1_company_proto protoreflect.FileDescriptor

const file_bvb_dividends_v1_company_proto_rawDesc = "" +
	"\n" +
	"\x1ebvb/dividends/v1/company.proto\x12\x10bvb.dividends.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x02\n" +
	"\aCompany\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1b\n" +
	"\x06symbol\x18\x02 \x01(\tB\x03\xe0A\x03R\x06symbol\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\x03\xe0A\x03R\vdisplayName\x12@\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime:O\xeaAL\n" +
	"!bvb-dividends.example.com/Company\x12\x13companies/{company}*\tcompanies2\acompanyBz\n" +
	"\x14com.bvb.dividends.v1B\fCompanyProtoP\x01ZRgithub.com/CodrinSocol/bvb-dividends-ro/libs/genproto/bvb/dividends/v1;dividendsv1b\x06proto3"

var (
	file_bvb_dividends_v1_company_proto_rawDescOnce sync.Once
	file_bvb_dividends_v1_company_proto_rawDescData []byte
)

func file_bvb_dividends_v1_company_proto_rawDescGZIP() []byte {
	file_bvb_dividends_v1_company_proto_rawDescOnce.Do(func() {
		file_bvb_dividends_v1_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bvb_dividends_v1_company_proto_rawDesc), len(file_bvb_dividends_v1_company_proto_rawDesc)))
	})
	return file_bvb_dividends_v1_company_proto_rawDescData
}

var file_bvb_dividends_v1_company_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bvb_dividends_v1_company_proto_goTypes = []any{
	(*Company)(nil),               // 0: bvb.dividends.v1.Company
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_bvb_dividends_v1_company_proto_depIdxs = []int32{
	1, // 0: bvb.dividends.v1.Company.create_time:type_name -> google.protobuf.Timestamp
	1, // 1: bvb.dividends.v1.Company.update_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bvb_dividends_v1_company_proto_init() }
func file_bvb_dividends_v1_company_proto_init() {
	if File_bvb_dividends_v1_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bvb_dividends_v1_company_proto_rawDesc), len(file_bvb_dividends_v1_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bvb_dividends_v1_company_proto_goTypes,
		DependencyIndexes: file_bvb_dividends_v1_company_proto_depIdxs,
		MessageInfos:      file_bvb_dividends_v1_company_proto_msgTypes,
	}.Build()
	File_bvb_dividends_v1_company_proto = out.File
	file_bvb_dividends_v1_company_proto_goTypes = nil
	file_bvb_dividends_v1_company_proto_depIdxs = nil
}
