// Copyright 2026 The BVB Dividends Authors.
//
// The read-only public API for Bucharest Stock Exchange dividend data.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bvb/dividends/v1/dividends_service.proto

package dividendsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DividendsService_ListCompanies_FullMethodName = "/bvb.dividends.v1.DividendsService/ListCompanies"
	DividendsService_GetCompany_FullMethodName    = "/bvb.dividends.v1.DividendsService/GetCompany"
	DividendsService_ListDividends_FullMethodName = "/bvb.dividends.v1.DividendsService/ListDividends"
	DividendsService_GetDividend_FullMethodName   = "/bvb.dividends.v1.DividendsService/GetDividend"
)

// DividendsServiceClient is the client API for DividendsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Read-only access to companies and dividends on the Bucharest Stock Exchange.
//
// Data is imported from the BVB financials web service on a daily schedule.
// The API is public and unauthenticated; all methods are safe and idempotent.
type DividendsServiceClient interface {
	// Lists companies known to have announced dividends.
	ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...grpc.CallOption) (*ListCompaniesResponse, error)
	// Gets a single company.
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*Company, error)
	// Lists the dividends announced by a company.
	//
	// To list dividends across all companies, use `-` as the company ID in
	// `parent`, for example `companies/-`.
	ListDividends(ctx context.Context, in *ListDividendsRequest, opts ...grpc.CallOption) (*ListDividendsResponse, error)
	// Gets a single dividend.
	GetDividend(ctx context.Context, in *GetDividendRequest, opts ...grpc.CallOption) (*Dividend, error)
}

type dividendsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDividendsServiceClient(cc grpc.ClientConnInterface) DividendsServiceClient {
	return &dividendsServiceClient{cc}
}

func (c *dividendsServiceClient) ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...grpc.CallOption) (*ListCompaniesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCompaniesResponse)
	err := c.cc.Invoke(ctx, DividendsService_ListCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dividendsServiceClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*Company, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Company)
	err := c.cc.Invoke(ctx, DividendsService_GetCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dividendsServiceClient) ListDividends(ctx context.Context, in *ListDividendsRequest, opts ...grpc.CallOption) (*ListDividendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDividendsResponse)
	err := c.cc.Invoke(ctx, DividendsService_ListDividends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dividendsServiceClient) GetDividend(ctx context.Context, in *GetDividendRequest, opts ...grpc.CallOption) (*Dividend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dividend)
	err := c.cc.Invoke(ctx, DividendsService_GetDividend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DividendsServiceServer is the server API for DividendsService service.
// All implementations should embed UnimplementedDividendsServiceServer
// for forward compatibility.
//
// Read-only access to companies and dividends on the Bucharest Stock Exchange.
//
// Data is imported from the BVB financials web service on a daily schedule.
// The API is public and unauthenticated; all methods are safe and idempotent.
type DividendsServiceServer interface {
	// Lists companies known to have announced dividends.
	ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesResponse, error)
	// Gets a single company.
	GetCompany(context.Context, *GetCompanyRequest) (*Company, error)
	// Lists the dividends announced by a company.
	//
	// To list dividends across all companies, use `-` as the company ID in
	// `parent`, for example `companies/-`.
	ListDividends(context.Context, *ListDividendsRequest) (*ListDividendsResponse, error)
	// Gets a single dividend.
	GetDividend(context.Context, *GetDividendRequest) (*Dividend, error)
}

// UnimplementedDividendsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDividendsServiceServer struct{}

func (UnimplementedDividendsServiceServer) ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCompanies not implemented")
}
func (UnimplementedDividendsServiceServer) GetCompany(context.Context, *GetCompanyRequest) (*Company, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompany not implemented")
}
func (UnimplementedDividendsServiceServer) ListDividends(context.Context, *ListDividendsRequest) (*ListDividendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDividends not implemented")
}
func (UnimplementedDividendsServiceServer) GetDividend(context.Context, *GetDividendRequest) (*Dividend, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDividend not implemented")
}
func (UnimplementedDividendsServiceServer) testEmbeddedByValue() {}

// UnsafeDividendsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DividendsServiceServer will
// result in compilation errors.
type UnsafeDividendsServiceServer interface {
	mustEmbedUnimplementedDividendsServiceServer()
}

func RegisterDividendsServiceServer(s grpc.ServiceRegistrar, srv DividendsServiceServer) {
	// If the following call panics, it indicates UnimplementedDividendsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DividendsService_ServiceDesc, srv)
}

func _DividendsService_ListCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DividendsServiceServer).ListCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DividendsService_ListCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DividendsServiceServer).ListCompanies(ctx, req.(*ListCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DividendsService_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DividendsServiceServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DividendsService_GetCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DividendsServiceServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DividendsService_ListDividends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDividendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DividendsServiceServer).ListDividends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DividendsService_ListDividends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DividendsServiceServer).ListDividends(ctx, req.(*ListDividendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DividendsService_GetDividend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDividendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DividendsServiceServer).GetDividend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DividendsService_GetDividend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DividendsServiceServer).GetDividend(ctx, req.(*GetDividendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DividendsService_ServiceDesc is the grpc.ServiceDesc for DividendsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DividendsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bvb.dividends.v1.DividendsService",
	HandlerType: (*DividendsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCompanies",
			Handler:    _DividendsService_ListCompanies_Handler,
		},
		{
			MethodName: "GetCompany",
			Handler:    _DividendsService_GetCompany_Handler,
		},
		{
			MethodName: "ListDividends",
			Handler:    _DividendsService_ListDividends_Handler,
		},
		{
			MethodName: "GetDividend",
			Handler:    _DividendsService_GetDividend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bvb/dividends/v1/dividends_service.proto",
}
