// Copyright 2026 The BVB Dividends Authors.
//
// Resource definitions for dividends announced on the Bucharest Stock Exchange.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: bvb/dividends/v1/dividend.proto

package dividendsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The stage a dividend has reached in its lifecycle.
//
// Derived from the dividend's schedule at read time; it is not stored.
type Dividend_State int32

const (
	// The default value. This value is unused.
	Dividend_STATE_UNSPECIFIED Dividend_State = 0
	// Announced, and the ex-dividend date is still in the future. Buying the
	// share today still entitles the holder to this dividend.
	Dividend_STATE_ANNOUNCED Dividend_State = 1
	// The ex-dividend date has passed but payment has not started.
	Dividend_STATE_EX_PASSED Dividend_State = 2
	// The payment window is currently open.
	Dividend_STATE_PAYING Dividend_State = 3
	// The payment window has closed.
	Dividend_STATE_PAID Dividend_State = 4
	// BVB did not report an ex-dividend date, so the stage cannot be derived.
	Dividend_STATE_UNDATED Dividend_State = 5
)

// Enum value maps for Dividend_State.
var (
	Dividend_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_ANNOUNCED",
		2: "STATE_EX_PASSED",
		3: "STATE_PAYING",
		4: "STATE_PAID",
		5: "STATE_UNDATED",
	}
	Dividend_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_ANNOUNCED":   1,
		"STATE_EX_PASSED":   2,
		"STATE_PAYING":      3,
		"STATE_PAID":        4,
		"STATE_UNDATED":     5,
	}
)

func (x Dividend_State) Enum() *Dividend_State {
	p := new(Dividend_State)
	*p = x
	return p
}

func (x Dividend_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dividend_State) Descriptor() protoreflect.EnumDescriptor {
	return file_bvb_dividends_v1_dividend_proto_enumTypes[0].Descriptor()
}

func (Dividend_State) Type() protoreflect.EnumType {
	return &file_bvb_dividends_v1_dividend_proto_enumTypes[0]
}

func (x Dividend_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Dividend_State.Descriptor instead.
func (Dividend_State) EnumDescriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividend_proto_rawDescGZIP(), []int{0, 0}
}

// A dividend announced by a company listed on the Bucharest Stock Exchange.
//
// A dividend is identified by the company that declared it, the fiscal year it
// relates to, its type, and its ex-dividend date. That tuple is stable across
// imports, so a dividend keeps the same resource name for its whole lifetime.
type Dividend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The resource name of the dividend.
	//
	// Format: `companies/{company}/dividends/{dividend}`, for example
	// `companies/SNP/dividends/8f14e45f-ceea-5a04-a6f3-2f4b1a9c0d33`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output only. The fiscal year the dividend relates to, for example `2025`.
	Year int32 `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	// Output only. The type of dividend as reported by BVB, for example `cash`.
	//
	// This is an open set owned by BVB rather than by this API, so it is
	// represented as a string and passed through unmodified.
	DividendType string `protobuf:"bytes,3,opt,name=dividend_type,json=dividendType,proto3" json:"dividend_type,omitempty"`
	// Output only. Gross dividend per share payable to natural persons, before
	// withholding tax.
	GrossPerShareNaturalPerson *money.Money `protobuf:"bytes,4,opt,name=gross_per_share_natural_person,json=grossPerShareNaturalPerson,proto3" json:"gross_per_share_natural_person,omitempty"`
	// Output only. Gross dividend per share payable to legal persons, before
	// withholding tax.
	GrossPerShareLegalPerson *money.Money `protobuf:"bytes,5,opt,name=gross_per_share_legal_person,json=grossPerShareLegalPerson,proto3" json:"gross_per_share_legal_person,omitempty"`
	// Output only. The total amount distributed across all shares.
	TotalAmount *money.Money `protobuf:"bytes,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Output only. The key dates of the dividend.
	Schedule *Schedule `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Output only. How the dividend is paid out, as described by BVB, for example
	// `bank transfer`.
	DistributionMethod string `protobuf:"bytes,8,opt,name=distribution_method,json=distributionMethod,proto3" json:"distribution_method,omitempty"`
	// Output only. The stage this dividend has reached, derived from `schedule`
	// at the time of the request.
	State Dividend_State `protobuf:"varint,9,opt,name=state,proto3,enum=bvb.dividends.v1.Dividend_State" json:"state,omitempty"`
	// Output only. The time this dividend was first imported from BVB.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. The time this dividend was last refreshed from BVB.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dividend) Reset() {
	*x = Dividend{}
	mi := &file_bvb_dividends_v1_dividend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dividend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dividend) ProtoMessage() {}

func (x *Dividend) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dividend.ProtoReflect.Descriptor instead.
func (*Dividend) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividend_proto_rawDescGZIP(), []int{0}
}

func (x *Dividend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dividend) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Dividend) GetDividendType() string {
	if x != nil {
		return x.DividendType
	}
	return ""
}

func (x *Dividend) GetGrossPerShareNaturalPerson() *money.Money {
	if x != nil {
		return x.GrossPerShareNaturalPerson
	}
	return nil
}

func (x *Dividend) GetGrossPerShareLegalPerson() *money.Money {
	if x != nil {
		return x.GrossPerShareLegalPerson
	}
	return nil
}

func (x *Dividend) GetTotalAmount() *money.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *Dividend) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *Dividend) GetDistributionMethod() string {
	if x != nil {
		return x.DistributionMethod
	}
	return ""
}

func (x *Dividend) GetState() Dividend_State {
	if x != nil {
		return x.State
	}
	return Dividend_STATE_UNSPECIFIED
}

func (x *Dividend) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Dividend) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// The key dates of a dividend.
//
// Every date is optional: BVB publishes them progressively as a dividend moves
// from announcement to payment, so an early-stage dividend has most of these
// unset. Absent dates are unset rather than zero.
type Schedule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The date the dividend was announced.
	AnnouncementDate *date.Date `protobuf:"bytes,1,opt,name=announcement_date,json=announcementDate,proto3" json:"announcement_date,omitempty"`
	// The reference date used for the general meeting of shareholders.
	GmsReferenceDate *date.Date `protobuf:"bytes,2,opt,name=gms_reference_date,json=gmsReferenceDate,proto3" json:"gms_reference_date,omitempty"`
	// The date of the general meeting of shareholders that approved the dividend.
	GmsDate *date.Date `protobuf:"bytes,3,opt,name=gms_date,json=gmsDate,proto3" json:"gms_date,omitempty"`
	// The date on which share ownership is recorded for entitlement.
	RecordDate *date.Date `protobuf:"bytes,4,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	// The first date on which the share trades without entitlement to this
	// dividend. Buying on or after this date does not earn the dividend.
	ExDividendDate *date.Date `protobuf:"bytes,5,opt,name=ex_dividend_date,json=exDividendDate,proto3" json:"ex_dividend_date,omitempty"`
	// The first date on which the dividend is paid.
	PaymentStartDate *date.Date `protobuf:"bytes,6,opt,name=payment_start_date,json=paymentStartDate,proto3" json:"payment_start_date,omitempty"`
	// The last date on which the dividend is paid.
	PaymentEndDate *date.Date `protobuf:"bytes,7,opt,name=payment_end_date,json=paymentEndDate,proto3" json:"payment_end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_bvb_dividends_v1_dividend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividend_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetAnnouncementDate() *date.Date {
	if x != nil {
		return x.AnnouncementDate
	}
	return nil
}

func (x *Schedule) GetGmsReferenceDate() *date.Date {
	if x != nil {
		return x.GmsReferenceDate
	}
	return nil
}

func (x *Schedule) GetGmsDate() *date.Date {
	if x != nil {
		return x.GmsDate
	}
	return nil
}

func (x *Schedule) GetRecordDate() *date.Date {
	if x != nil {
		return x.RecordDate
	}
	return nil
}

func (x *Schedule) GetExDividendDate() *date.Date {
	if x != nil {
		return x.ExDividendDate
	}
	return nil
}

func (x *Schedule) GetPaymentStartDate() *date.Date {
	if x != nil {
		return x.PaymentStartDate
	}
	return nil
}

func (x *Schedule) GetPaymentEndDate() *date.Date {
	if x != nil {
		return x.PaymentEndDate
	}
	return nil
}

var File_bvb_dividends_v1_dividend_proto protoreflect.FileDescriptor

const file_bvb_dividends_v1_dividend_proto_rawDesc = "" +
	"\n" +
	"\x1fbvb/dividends/v1/dividend.proto\x12\x10bvb.dividends.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\x1a\x17google/type/money.proto\"\xf3\x06\n" +
	"\bDividend\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x17\n" +
	"\x04year\x18\x02 \x01(\x05B\x03\xe0A\x03R\x04year\x12(\n" +
	"\rdividend_type\x18\x03 \x01(\tB\x03\xe0A\x03R\fdividendType\x12[\n" +
	"\x1egross_per_share_natural_person\x18\x04 \x01(\v2\x12.google.type.MoneyB\x03\xe0A\x03R\x1agrossPerShareNaturalPerson\x12W\n" +
	"\x1cgross_per_share_legal_person\x18\x05 \x01(\v2\x12.google.type.MoneyB\x03\xe0A\x03R\x18grossPerShareLegalPerson\x12:\n" +
	"\ftotal_amount\x18\x06 \x01(\v2\x12.google.type.MoneyB\x03\xe0A\x03R\vtotalAmount\x12;\n" +
	"\bschedule\x18\a \x01(\v2\x1a.bvb.dividends.v1.ScheduleB\x03\xe0A\x03R\bschedule\x124\n" +
	"\x13distribution_method\x18\b \x01(\tB\x03\xe0A\x03R\x12distributionMethod\x12;\n" +
	"\x05state\x18\t \x01(\x0e2 .bvb.dividends.v1.Dividend.StateB\x03\xe0A\x03R\x05state\x12@\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\"}\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATE_ANNOUNCED\x10\x01\x12\x13\n" +
	"\x0fSTATE_EX_PASSED\x10\x02\x12\x10\n" +
	"\fSTATE_PAYING\x10\x03\x12\x0e\n" +
	"\n" +
	"STATE_PAID\x10\x04\x12\x11\n" +
	"\rSTATE_UNDATED\x10\x05:f\xeaAc\n" +
	"\"bvb-dividends.example.com/Dividend\x12(companies/{company}/dividends/{dividend}*\tdividends2\bdividend\"\xcb\x03\n" +
	"\bSchedule\x12C\n" +
	"\x11announcement_date\x18\x01 \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\x10announcementDate\x12D\n" +
	"\x12gms_reference_date\x18\x02 \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\x10gmsReferenceDate\x121\n" +
	"\bgms_date\x18\x03 \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\agmsDate\x127\n" +
	"\vrecord_date\x18\x04 \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\n" +
	"recordDate\x12@\n" +
	"\x10ex_dividend_date\x18\x05 \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\x0eexDividendDate\x12D\n" +
	"\x12payment_start_date\x18\x06 \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\x10paymentStartDate\x12@\n" +
	"\x10payment_end_date\x18\a \x01(\v2\x11.google.type.DateB\x03\xe0A\x01R\x0epaymentEndDateB{\n" +
	"\x14com.bvb.dividends.v1B\rDividendProtoP\x01ZRgithub.com/CodrinSocol/bvb-dividends-ro/libs/genproto/bvb/dividends/v1;dividendsv1b\x06proto3"

var (
	file_bvb_dividends_v1_dividend_proto_rawDescOnce sync.Once
	file_bvb_dividends_v1_dividend_proto_rawDescData []byte
)

func file_bvb_dividends_v1_dividend_proto_rawDescGZIP() []byte {
	file_bvb_dividends_v1_dividend_proto_rawDescOnce.Do(func() {
		file_bvb_dividends_v1_dividend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bvb_dividends_v1_dividend_proto_rawDesc), len(file_bvb_dividends_v1_dividend_proto_rawDesc)))
	})
	return file_bvb_dividends_v1_dividend_proto_rawDescData
}

var file_bvb_dividends_v1_dividend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bvb_dividends_v1_dividend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bvb_dividends_v1_dividend_proto_goTypes = []any{
	(Dividend_State)(0),           // 0: bvb.dividends.v1.Dividend.State
	(*Dividend)(nil),              // 1: bvb.dividends.v1.Dividend
	(*Schedule)(nil),              // 2: bvb.dividends.v1.Schedule
	(*money.Money)(nil),           // 3: google.type.Money
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*date.Date)(nil),             // 5: google.type.Date
}
var file_bvb_dividends_v1_dividend_proto_depIdxs = []int32{
	3,  // 0: bvb.dividends.v1.Dividend.gross_per_share_natural_person:type_name -> google.type.Money
	3,  // 1: bvb.dividends.v1.Dividend.gross_per_share_legal_person:type_name -> google.type.Money
	3,  // 2: bvb.dividends.v1.Dividend.total_amount:type_name -> google.type.Money
	2,  // 3: bvb.dividends.v1.Dividend.schedule:type_name -> bvb.dividends.v1.Schedule
	0,  // 4: bvb.dividends.v1.Dividend.state:type_name -> bvb.dividends.v1.Dividend.State
	4,  // 5: bvb.dividends.v1.Dividend.create_time:type_name -> google.protobuf.Timestamp
	4,  // 6: bvb.dividends.v1.Dividend.update_time:type_name -> google.protobuf.Timestamp
	5,  // 7: bvb.dividends.v1.Schedule.announcement_date:type_name -> google.type.Date
	5,  // 8: bvb.dividends.v1.Schedule.gms_reference_date:type_name -> google.type.Date
	5,  // 9: bvb.dividends.v1.Schedule.gms_date:type_name -> google.type.Date
	5,  // 10: bvb.dividends.v1.Schedule.record_date:type_name -> google.type.Date
	5,  // 11: bvb.dividends.v1.Schedule.ex_dividend_date:type_name -> google.type.Date
	5,  // 12: bvb.dividends.v1.Schedule.payment_start_date:type_name -> google.type.Date
	5,  // 13: bvb.dividends.v1.Schedule.payment_end_date:type_name -> google.type.Date
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_bvb_dividends_v1_dividend_proto_init() }
func file_bvb_dividends_v1_dividend_proto_init() {
	if File_bvb_dividends_v1_dividend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bvb_dividends_v1_dividend_proto_rawDesc), len(file_bvb_dividends_v1_dividend_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bvb_dividends_v1_dividend_proto_goTypes,
		DependencyIndexes: file_bvb_dividends_v1_dividend_proto_depIdxs,
		EnumInfos:         file_bvb_dividends_v1_dividend_proto_enumTypes,
		MessageInfos:      file_bvb_dividends_v1_dividend_proto_msgTypes,
	}.Build()
	File_bvb_dividends_v1_dividend_proto = out.File
	file_bvb_dividends_v1_dividend_proto_goTypes = nil
	file_bvb_dividends_v1_dividend_proto_depIdxs = nil
}
