// Copyright 2026 The BVB Dividends Authors.
//
// The read-only public API for Bucharest Stock Exchange dividend data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: bvb/dividends/v1/dividends_service.proto

package dividendsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [DividendsService.ListCompanies][bvb.dividends.v1.DividendsService.ListCompanies].
type ListCompaniesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The maximum number of companies to return.
	//
	// The service may return fewer. If unspecified, at most 50 companies are
	// returned. The maximum value is 1000; values above 1000 are coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListCompanies` call.
	//
	// Provide this to retrieve the subsequent page. When paginating, all other
	// parameters must match the call that provided the page token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. An [AIP-160](https://google.aip.dev/160) filter expression.
	//
	// Filterable fields: `symbol`, `display_name`, `create_time`, `update_time`.
	//
	// Example: `symbol = "SNP" OR display_name : "BANCA"`.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to sort by, as described in
	// [AIP-132](https://google.aip.dev/132).
	//
	// Sortable fields: `symbol`, `display_name`, `create_time`, `update_time`.
	// The default is `symbol`. Append ` desc` to a field to reverse its order,
	// for example `display_name desc`.
	OrderBy       string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesRequest) Reset() {
	*x = ListCompaniesRequest{}
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesRequest) ProtoMessage() {}

func (x *ListCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesRequest.ProtoReflect.Descriptor instead.
func (*ListCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListCompaniesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCompaniesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCompaniesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCompaniesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// Response message for
// [DividendsService.ListCompanies][bvb.dividends.v1.DividendsService.ListCompanies].
type ListCompaniesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The companies on this page, in the requested order.
	Companies []*Company `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	// A token to retrieve the next page, or empty if this is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of companies matching the filter, across all pages.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompaniesResponse) Reset() {
	*x = ListCompaniesResponse{}
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompaniesResponse) ProtoMessage() {}

func (x *ListCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompaniesResponse.ProtoReflect.Descriptor instead.
func (*ListCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListCompaniesResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *ListCompaniesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCompaniesResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Request message for
// [DividendsService.GetCompany][bvb.dividends.v1.DividendsService.GetCompany].
type GetCompanyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the company.
	//
	// Format: `companies/{company}`, for example `companies/SNP`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompanyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for
// [DividendsService.ListDividends][bvb.dividends.v1.DividendsService.ListDividends].
type ListDividendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The company whose dividends are listed.
	//
	// Format: `companies/{company}`, for example `companies/SNP`. Use
	// `companies/-` to list dividends across all companies, as described in
	// [AIP-159](https://google.aip.dev/159).
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of dividends to return.
	//
	// The service may return fewer. If unspecified, at most 50 dividends are
	// returned. The maximum value is 1000; values above 1000 are coerced to 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token received from a previous `ListDividends` call.
	//
	// Provide this to retrieve the subsequent page. When paginating, all other
	// parameters must match the call that provided the page token.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. An [AIP-160](https://google.aip.dev/160) filter expression.
	//
	// Filterable fields: `company`, `year`, `dividend_type`,
	// `schedule.ex_dividend_date`, `schedule.record_date`,
	// `schedule.payment_start_date`, `schedule.payment_end_date`,
	// `schedule.announcement_date`, `create_time`, `update_time`.
	//
	// Dates are compared against `YYYY-MM-DD` string literals. To match
	// dividends whose date is not set, compare against `null`.
	//
	// Example:
	// `year >= 2024 AND schedule.ex_dividend_date > "2026-01-01"`.
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. A comma-separated list of fields to sort by, as described in
	// [AIP-132](https://google.aip.dev/132).
	//
	// Sortable fields: `company`, `year`, `schedule.ex_dividend_date`,
	// `schedule.payment_start_date`, `create_time`, `update_time`. The default is
	// `schedule.ex_dividend_date desc`. Append ` desc` to a field to reverse its
	// order.
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDividendsRequest) Reset() {
	*x = ListDividendsRequest{}
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDividendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDividendsRequest) ProtoMessage() {}

func (x *ListDividendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDividendsRequest.ProtoReflect.Descriptor instead.
func (*ListDividendsRequest) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListDividendsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListDividendsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDividendsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListDividendsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListDividendsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// Response message for
// [DividendsService.ListDividends][bvb.dividends.v1.DividendsService.ListDividends].
type ListDividendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dividends on this page, in the requested order.
	Dividends []*Dividend `protobuf:"bytes,1,rep,name=dividends,proto3" json:"dividends,omitempty"`
	// A token to retrieve the next page, or empty if this is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of dividends matching the filter, across all pages.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDividendsResponse) Reset() {
	*x = ListDividendsResponse{}
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDividendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDividendsResponse) ProtoMessage() {}

func (x *ListDividendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDividendsResponse.ProtoReflect.Descriptor instead.
func (*ListDividendsResponse) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListDividendsResponse) GetDividends() []*Dividend {
	if x != nil {
		return x.Dividends
	}
	return nil
}

func (x *ListDividendsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListDividendsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Request message for
// [DividendsService.GetDividend][bvb.dividends.v1.DividendsService.GetDividend].
type GetDividendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the dividend.
	//
	// Format: `companies/{company}/dividends/{dividend}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDividendRequest) Reset() {
	*x = GetDividendRequest{}
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDividendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDividendRequest) ProtoMessage() {}

func (x *GetDividendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bvb_dividends_v1_dividends_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDividendRequest.ProtoReflect.Descriptor instead.
func (*GetDividendRequest) Descriptor() ([]byte, []int) {
	return file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDividendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_bvb_dividends_v1_dividends_service_proto protoreflect.FileDescriptor

const file_bvb_dividends_v1_dividends_service_proto_rawDesc = "" +
	"\n" +
	"(bvb/dividends/v1/dividends_service.proto\x12\x10bvb.dividends.v1\x1a\x1ebvb/dividends/v1/company.proto\x1a\x1fbvb/dividends/v1/dividend.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x99\x01\n" +
	"\x14ListCompaniesRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x03 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x04 \x01(\tB\x03\xe0A\x01R\aorderBy\"\x97\x01\n" +
	"\x15ListCompaniesResponse\x127\n" +
	"\tcompanies\x18\x01 \x03(\v2\x19.bvb.dividends.v1.CompanyR\tcompanies\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"R\n" +
	"\x11GetCompanyRequest\x12=\n" +
	"\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n" +
	"!bvb-dividends.example.com/CompanyR\x04name\"\xdd\x01\n" +
	"\x14ListDividendsRequest\x12B\n" +
	"\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12\"bvb-dividends.example.com/DividendR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tB\x03\xe0A\x01R\aorderBy\"\x98\x01\n" +
	"\x15ListDividendsResponse\x128\n" +
	"\tdividends\x18\x01 \x03(\v2\x1a.bvb.dividends.v1.DividendR\tdividends\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"T\n" +
	"\x12GetDividendRequest\x12>\n" +
	"\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n" +
	"\"bvb-dividends.example.com/DividendR\x04name2\xbb\x04\n" +
	"\x10DividendsService\x12w\n" +
	"\rListCompanies\x12&.bvb.dividends.v1.ListCompaniesRequest\x1a'.bvb.dividends.v1.ListCompaniesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/companies\x12s\n" +
	"\n" +
	"GetCompany\x12#.bvb.dividends.v1.GetCompanyRequest\x1a\x19.bvb.dividends.v1.Company\"%\xdaA\x04name\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{name=companies/*}\x12\x95\x01\n" +
	"\rListDividends\x12&.bvb.dividends.v1.ListDividendsRequest\x1a'.bvb.dividends.v1.ListDividendsResponse\"3\xdaA\x06parent\x82\xd3\xe4\x93\x02$\x12\"/v1/{parent=companies/*}/dividends\x12\x82\x01\n" +
	"\vGetDividend\x12$.bvb.dividends.v1.GetDividendRequest\x1a\x1a.bvb.dividends.v1.Dividend\"1\xdaA\x04name\x82\xd3\xe4\x93\x02$\x12\"/v1/{name=companies/*/dividends/*}\x1a\x1c\xcaA\x19bvb-dividends.example.comB\x83\x01\n" +
	"\x14com.bvb.dividends.v1B\x15DividendsServiceProtoP\x01ZRgithub.com/CodrinSocol/bvb-dividends-ro/libs/genproto/bvb/dividends/v1;dividendsv1b\x06proto3"

var (
	file_bvb_dividends_v1_dividends_service_proto_rawDescOnce sync.Once
	file_bvb_dividends_v1_dividends_service_proto_rawDescData []byte
)

func file_bvb_dividends_v1_dividends_service_proto_rawDescGZIP() []byte {
	file_bvb_dividends_v1_dividends_service_proto_rawDescOnce.Do(func() {
		file_bvb_dividends_v1_dividends_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bvb_dividends_v1_dividends_service_proto_rawDesc), len(file_bvb_dividends_v1_dividends_service_proto_rawDesc)))
	})
	return file_bvb_dividends_v1_dividends_service_proto_rawDescData
}

var file_bvb_dividends_v1_dividends_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bvb_dividends_v1_dividends_service_proto_goTypes = []any{
	(*ListCompaniesRequest)(nil),  // 0: bvb.dividends.v1.ListCompaniesRequest
	(*ListCompaniesResponse)(nil), // 1: bvb.dividends.v1.ListCompaniesResponse
	(*GetCompanyRequest)(nil),     // 2: bvb.dividends.v1.GetCompanyRequest
	(*ListDividendsRequest)(nil),  // 3: bvb.dividends.v1.ListDividendsRequest
	(*ListDividendsResponse)(nil), // 4: bvb.dividends.v1.ListDividendsResponse
	(*GetDividendRequest)(nil),    // 5: bvb.dividends.v1.GetDividendRequest
	(*Company)(nil),               // 6: bvb.dividends.v1.Company
	(*Dividend)(nil),              // 7: bvb.dividends.v1.Dividend
}
var file_bvb_dividends_v1_dividends_service_proto_depIdxs = []int32{
	6, // 0: bvb.dividends.v1.ListCompaniesResponse.companies:type_name -> bvb.dividends.v1.Company
	7, // 1: bvb.dividends.v1.ListDividendsResponse.dividends:type_name -> bvb.dividends.v1.Dividend
	0, // 2: bvb.dividends.v1.DividendsService.ListCompanies:input_type -> bvb.dividends.v1.ListCompaniesRequest
	2, // 3: bvb.dividends.v1.DividendsService.GetCompany:input_type -> bvb.dividends.v1.GetCompanyRequest
	3, // 4: bvb.dividends.v1.DividendsService.ListDividends:input_type -> bvb.dividends.v1.ListDividendsRequest
	5, // 5: bvb.dividends.v1.DividendsService.GetDividend:input_type -> bvb.dividends.v1.GetDividendRequest
	1, // 6: bvb.dividends.v1.DividendsService.ListCompanies:output_type -> bvb.dividends.v1.ListCompaniesResponse
	6, // 7: bvb.dividends.v1.DividendsService.GetCompany:output_type -> bvb.dividends.v1.Company
	4, // 8: bvb.dividends.v1.DividendsService.ListDividends:output_type -> bvb.dividends.v1.ListDividendsResponse
	7, // 9: bvb.dividends.v1.DividendsService.GetDividend:output_type -> bvb.dividends.v1.Dividend
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bvb_dividends_v1_dividends_service_proto_init() }
func file_bvb_dividends_v1_dividends_service_proto_init() {
	if File_bvb_dividends_v1_dividends_service_proto != nil {
		return
	}
	file_bvb_dividends_v1_company_proto_init()
	file_bvb_dividends_v1_dividend_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bvb_dividends_v1_dividends_service_proto_rawDesc), len(file_bvb_dividends_v1_dividends_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bvb_dividends_v1_dividends_service_proto_goTypes,
		DependencyIndexes: file_bvb_dividends_v1_dividends_service_proto_depIdxs,
		MessageInfos:      file_bvb_dividends_v1_dividends_service_proto_msgTypes,
	}.Build()
	File_bvb_dividends_v1_dividends_service_proto = out.File
	file_bvb_dividends_v1_dividends_service_proto_goTypes = nil
	file_bvb_dividends_v1_dividends_service_proto_depIdxs = nil
}
