/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists companies known to have announced dividends. */
        get: operations["DividendsService_ListCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies/{company}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets a single company. */
        get: operations["DividendsService_GetCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies/{company}/dividends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists the dividends announced by a company.
         *
         *      To list dividends across all companies, use `-` as the company ID in
         *      `parent`, for example `companies/-`.
         */
        get: operations["DividendsService_ListDividends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies/{company}/dividends/{dividend}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets a single dividend. */
        get: operations["DividendsService_GetDividend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A company listed on the Bucharest Stock Exchange (Bursa de Valori Bucuresti).
         *
         *      Companies are discovered from the BVB financials web service; they are never
         *      created directly through this API.
         */
        Company: {
            /**
             * @description Identifier. The resource name of the company.
             *
             *      Format: `companies/{company}`, where `{company}` is the BVB ticker symbol,
             *      for example `companies/SNP`.
             */
            name?: string;
            /**
             * @description Output only. The BVB ticker symbol, for example `SNP`.
             *
             *      This is the same value as the `{company}` segment of `name`, exposed as a
             *      field for convenience and filtering.
             */
            readonly symbol?: string;
            /**
             * @description Output only. The full legal name of the company, for example
             *      `OMV PETROM S.A.`, as reported by BVB.
             */
            readonly displayName?: string;
            /**
             * Format: date-time
             * @description Output only. The time this company was first imported from BVB.
             */
            readonly createTime?: string;
            /**
             * Format: date-time
             * @description Output only. The time this company was last refreshed from BVB.
             */
            readonly updateTime?: string;
        };
        /**
         * @description A dividend announced by a company listed on the Bucharest Stock Exchange.
         *
         *      A dividend is identified by the company that declared it, the fiscal year it
         *      relates to, its type, and its ex-dividend date. That tuple is stable across
         *      imports, so a dividend keeps the same resource name for its whole lifetime.
         */
        Dividend: {
            /**
             * @description Identifier. The resource name of the dividend.
             *
             *      Format: `companies/{company}/dividends/{dividend}`, for example
             *      `companies/SNP/dividends/8f14e45f-ceea-5a04-a6f3-2f4b1a9c0d33`.
             */
            name?: string;
            /**
             * Format: int32
             * @description Output only. The fiscal year the dividend relates to, for example `2025`.
             */
            readonly year?: number;
            /**
             * @description Output only. The type of dividend as reported by BVB, for example `cash`.
             *
             *      This is an open set owned by BVB rather than by this API, so it is
             *      represented as a string and passed through unmodified.
             */
            readonly dividendType?: string;
            /**
             * @description Output only. Gross dividend per share payable to natural persons, before
             *      withholding tax.
             */
            readonly grossPerShareNaturalPerson?: components["schemas"]["Money"];
            /**
             * @description Output only. Gross dividend per share payable to legal persons, before
             *      withholding tax.
             */
            readonly grossPerShareLegalPerson?: components["schemas"]["Money"];
            /** @description Output only. The total amount distributed across all shares. */
            readonly totalAmount?: components["schemas"]["Money"];
            /** @description Output only. The key dates of the dividend. */
            readonly schedule?: components["schemas"]["Schedule"];
            /**
             * @description Output only. How the dividend is paid out, as described by BVB, for example
             *      `bank transfer`.
             */
            readonly distributionMethod?: string;
            /**
             * Format: enum
             * @description Output only. The stage this dividend has reached, derived from `schedule`
             *      at the time of the request.
             * @enum {string}
             */
            readonly state?: "STATE_UNSPECIFIED" | "STATE_ANNOUNCED" | "STATE_EX_PASSED" | "STATE_PAYING" | "STATE_PAID" | "STATE_UNDATED";
            /**
             * Format: date-time
             * @description Output only. The time this dividend was first imported from BVB.
             */
            readonly createTime?: string;
            /**
             * Format: date-time
             * @description Output only. The time this dividend was last refreshed from BVB.
             */
            readonly updateTime?: string;
        };
        /**
         * @description Response message for
         *      [DividendsService.ListCompanies][bvb.dividends.v1.DividendsService.ListCompanies].
         */
        ListCompaniesResponse: {
            /** @description The companies on this page, in the requested order. */
            companies?: components["schemas"]["Company"][];
            /** @description A token to retrieve the next page, or empty if this is the last page. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description The total number of companies matching the filter, across all pages.
             */
            totalSize?: number;
        };
        /**
         * @description Response message for
         *      [DividendsService.ListDividends][bvb.dividends.v1.DividendsService.ListDividends].
         */
        ListDividendsResponse: {
            /** @description The dividends on this page, in the requested order. */
            dividends?: components["schemas"]["Dividend"][];
            /** @description A token to retrieve the next page, or empty if this is the last page. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description The total number of dividends matching the filter, across all pages.
             */
            totalSize?: number;
        };
        /** @description Represents an amount of money with its currency type. */
        Money: {
            /** @description The three-letter currency code defined in ISO 4217. */
            currencyCode?: string;
            /**
             * @description The whole units of the amount.
             *      For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
             */
            units?: string;
            /**
             * Format: int32
             * @description Number of nano (10^-9) units of the amount.
             *      The value must be between -999,999,999 and +999,999,999 inclusive.
             *      If `units` is positive, `nanos` must be positive or zero.
             *      If `units` is zero, `nanos` can be positive, zero, or negative.
             *      If `units` is negative, `nanos` must be negative or zero.
             *      For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
             */
            nanos?: number;
        };
        /**
         * @description The key dates of a dividend.
         *
         *      Every date is optional: BVB publishes them progressively as a dividend moves
         *      from announcement to payment, so an early-stage dividend has most of these
         *      unset. Absent dates are unset rather than zero.
         */
        Schedule: {
            /** @description The date the dividend was announced. */
            announcementDate?: components["schemas"]["GoogleTypeDate"];
            /** @description The reference date used for the general meeting of shareholders. */
            gmsReferenceDate?: components["schemas"]["GoogleTypeDate"];
            /** @description The date of the general meeting of shareholders that approved the dividend. */
            gmsDate?: components["schemas"]["GoogleTypeDate"];
            /** @description The date on which share ownership is recorded for entitlement. */
            recordDate?: components["schemas"]["GoogleTypeDate"];
            /**
             * @description The first date on which the share trades without entitlement to this
             *      dividend. Buying on or after this date does not earn the dividend.
             */
            exDividendDate?: components["schemas"]["GoogleTypeDate"];
            /** @description The first date on which the dividend is paid. */
            paymentStartDate?: components["schemas"]["GoogleTypeDate"];
            /** @description The last date on which the dividend is paid. */
            paymentEndDate?: components["schemas"]["GoogleTypeDate"];
        };
        /** @description A calendar date, as google.type.Date. A year on its own, or a year and month with a zero day, denotes a whole year or month. */
        GoogleTypeDate: {
            /**
             * Format: int32
             * @description Year of the date.
             */
            year?: number;
            /**
             * Format: int32
             * @description Month of the year, 1 to 12.
             */
            month?: number;
            /**
             * Format: int32
             * @description Day of the month, 1 to 31.
             */
            day?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DividendsService_ListCompanies: {
        parameters: {
            query?: {
                /**
                 * @description Optional. The maximum number of companies to return.
                 *
                 *      The service may return fewer. If unspecified, at most 50 companies are
                 *      returned. The maximum value is 1000; values above 1000 are coerced to 1000.
                 */
                pageSize?: number;
                /**
                 * @description Optional. A page token received from a previous `ListCompanies` call.
                 *
                 *      Provide this to retrieve the subsequent page. When paginating, all other
                 *      parameters must match the call that provided the page token.
                 */
                pageToken?: string;
                /**
                 * @description Optional. An [AIP-160](https://google.aip.dev/160) filter expression.
                 *
                 *      Filterable fields: `symbol`, `display_name`, `create_time`, `update_time`.
                 *
                 *      Example: `symbol = "SNP" OR display_name : "BANCA"`.
                 */
                filter?: string;
                /**
                 * @description Optional. A comma-separated list of fields to sort by, as described in
                 *      [AIP-132](https://google.aip.dev/132).
                 *
                 *      Sortable fields: `symbol`, `display_name`, `create_time`, `update_time`.
                 *      The default is `symbol`. Append ` desc` to a field to reverse its order,
                 *      for example `display_name desc`.
                 */
                orderBy?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCompaniesResponse"];
                };
            };
        };
    };
    DividendsService_GetCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The company id. */
                company: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
        };
    };
    DividendsService_ListDividends: {
        parameters: {
            query?: {
                /**
                 * @description Optional. The maximum number of dividends to return.
                 *
                 *      The service may return fewer. If unspecified, at most 50 dividends are
                 *      returned. The maximum value is 1000; values above 1000 are coerced to 1000.
                 */
                pageSize?: number;
                /**
                 * @description Optional. A page token received from a previous `ListDividends` call.
                 *
                 *      Provide this to retrieve the subsequent page. When paginating, all other
                 *      parameters must match the call that provided the page token.
                 */
                pageToken?: string;
                /**
                 * @description Optional. An [AIP-160](https://google.aip.dev/160) filter expression.
                 *
                 *      Filterable fields: `company`, `year`, `dividend_type`,
                 *      `schedule.ex_dividend_date`, `schedule.record_date`,
                 *      `schedule.payment_start_date`, `schedule.payment_end_date`,
                 *      `schedule.announcement_date`, `create_time`, `update_time`.
                 *
                 *      Dates are compared against `YYYY-MM-DD` string literals. To match
                 *      dividends whose date is not set, compare against `null`.
                 *
                 *      Example:
                 *      `year >= 2024 AND schedule.ex_dividend_date > "2026-01-01"`.
                 */
                filter?: string;
                /**
                 * @description Optional. A comma-separated list of fields to sort by, as described in
                 *      [AIP-132](https://google.aip.dev/132).
                 *
                 *      Sortable fields: `company`, `year`, `schedule.ex_dividend_date`,
                 *      `schedule.payment_start_date`, `create_time`, `update_time`. The default is
                 *      `schedule.ex_dividend_date desc`. Append ` desc` to a field to reverse its
                 *      order.
                 */
                orderBy?: string;
            };
            header?: never;
            path: {
                /** @description The company id. */
                company: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDividendsResponse"];
                };
            };
        };
    };
    DividendsService_GetDividend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The company id. */
                company: string;
                /** @description The dividend id. */
                dividend: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dividend"];
                };
            };
        };
    };
}
